"""create table birds with image

Revision ID: 2d361ccb60f5
Revises: b5afeadedf28
Create Date: 2024-01-20 14:49:43.906603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d361ccb60f5'
down_revision = 'b5afeadedf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
